### ISSUE TITLE
make_shelx: implicit single elements ignored in composition

### ISSUE THREAD

**Issue by dagewa** [instamatic-dev/edtools#20]
I was running `edtools.make_shelx` like this:
```
edtools.make_shelx -c 7.487 11.041 13.775 90 92.939 90 -s "P2(1)/n" -m C15 H12 N2 O
```
I just noticed that this does not produce `SFAC` values for the oxygen atom. It works okay if `O1` is used instead though.

This did not stop solving the structure :grin:, but as it is a silent omission it might be catching people out. Could we please recognise a plain `O` as if it were `O1`? Or at the very least report that not all of the composition line was processed?

**Comment by stefsmeets** [comment]
Good point, this is using a very simple regex: https://github.com/instamatic-dev/edtools/blob/cc0130888554fb38c52206f28003da6a4cb61594/edtools/make_shelx.py#L23
