### ISSUE TITLE
make_shelx: Wrong symmetry operations generated for space group Fd-3m

### ISSUE THREAD

**Issue by aurorateien** [instamatic-dev/edtools#22]
Hello, 
I tried using make_shelx for space group Fd-3m (no. 227), with the following command:
`edtools.make_shelx -c 5.43 5.43 5.43 90 90 90 -s"227" -m Si8`
But the LATT-number and the symmetry operations generated are wrong. LATT should be positive as the space group is centrosymmetric, although the generated ins shows -4. SHELXT was unable to solve the structure, as it could not identify Laue group from the SYMM instructions.

**Comment by stefsmeets** [comment]
Can you try the other setting? The first setting does not have the origin on a center of symmetry which is required for shelx.

`edtools.make_shelx -c 5.43 5.43 5.43 90 90 90 -s"227:2" -m Si8`

**Comment by aurorateien** [comment]
Thanks @stefsmeets ! It worked. Is there other space groups that have multiple settings as well?

**Comment by stefsmeets** [comment]
Yup, quite a few. It's easiest to check the International Tables Vol. A: https://it.iucr.org/A/ or the bilbao server: https://www.cryst.ehu.es/cgi-bin/cryst/programs/nph-getgen
